'use client'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { AppNav } from '../../../../components/layout/AppNavContext'
import Card from '../../../../components/ui/Card'
import Button from '../../../../components/ui/Button'
import { ArrowLeft, CheckCircle2, Clock3, Play, Wind } from 'lucide-react'

const details: Record<string, { title: string; description: string; duration: string; emoji: string; steps: string[] }> = {
  meditation: { title: '5-Minute Meditation', description: 'A short reset to help you return to the present moment.', duration: '5 minutes', emoji: '🧘', steps: ['Find a comfortable position.', 'Notice three slow breaths.', 'Let thoughts come and go without following them.'] },
  gratitude: { title: 'Gratitude Journaling', description: 'Shift your attention toward the small things that are carrying you.', duration: '10 minutes', emoji: '🌻', steps: ['Name one thing that felt good today.', 'Write why it mattered to you.', 'Notice how your body feels as you remember it.'] },
  breathing: { title: 'Breathing Exercise', description: 'Use a steady 4-7-8 rhythm to help your body soften.', duration: '3 minutes', emoji: '🌬️', steps: ['Breathe in for 4 counts.', 'Hold gently for 7 counts.', 'Exhale slowly for 8 counts.'] },
  nature: { title: 'Nature Walk', description: 'A mindful walk to reconnect with your senses and surroundings.', duration: '15 minutes', emoji: '🌿', steps: ['Look for five things you can see.', 'Notice four things you can feel.', 'Take one unhurried step at a time.'] },
  creative: { title: 'Creative Expression', description: 'Make something without judging the result.', duration: '20 minutes', emoji: '🎨', steps: ['Choose a colour that matches your mood.', 'Draw or write continuously for five minutes.', 'Keep what feels meaningful and let go of the rest.'] },
  detox: { title: 'Digital Detox', description: 'A quiet pause from notifications and scrolling.', duration: '30 minutes', emoji: '📵', steps: ['Put your phone on silent.', 'Choose one offline activity.', 'Return when you feel more settled.'] },
}

export default function ActivityDetailPage() { const { id } = useParams<{ id: string }>(); const activity = details[id] ?? details.meditation; const [started, setStarted] = useState(false); return <><AppNav title={activity.title} showBack/><div className="page-enter mx-auto max-w-3xl space-y-6 pb-8"><Link href="/app/activities" className="inline-flex items-center gap-2 text-sm text-warm-gray hover:text-plum"><ArrowLeft size={16}/> Back to activities</Link><Card className="overflow-hidden bg-white/80" padding="lg"><div className="flex h-40 items-center justify-center rounded-2xl bg-gradient-to-br from-plum to-terracotta text-7xl">{activity.emoji}</div><div className="mt-7 flex items-start justify-between gap-4"><div><h1 className="font-heading text-3xl font-semibold">{activity.title}</h1><p className="mt-2 text-sm leading-6 text-warm-gray">{activity.description}</p></div><span className="flex shrink-0 items-center gap-1 rounded-full bg-cream-dark px-3 py-1.5 text-xs text-warm-gray"><Clock3 size={13}/>{activity.duration}</span></div><div className="mt-8 space-y-3">{activity.steps.map((step,index)=><div key={step} className="flex items-center gap-3 rounded-xl bg-cream-dark/70 px-4 py-3 text-sm"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-plum text-xs font-semibold text-cream">{index+1}</span>{step}</div>)}</div>{started && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="mt-6 overflow-hidden rounded-2xl bg-sage/10 p-6 text-center"><motion.div animate={id === 'breathing' ? { scale: [1, 1.35, 1] } : { y: [0, -10, 0], rotate: [0, 4, -4, 0] }} transition={{ duration: id === 'breathing' ? 8 : 4, repeat: Infinity, ease: 'easeInOut' }} className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-gradient-to-br from-sage to-plum text-4xl shadow-medium">{activity.emoji}</motion.div><p className="mt-4 font-heading text-xl font-semibold text-plum">{id === 'breathing' ? 'Breathe in… and out…' : 'Take this moment for yourself.'}</p><p className="mt-1 text-sm text-warm-gray">Follow the rhythm. There is nowhere else you need to be.</p></motion.div>}<Button className="mt-8 w-full" onClick={() => setStarted((value) => !value)}><Play size={16}/>{started ? 'Pause activity' : 'Start activity'}</Button></Card><div className="flex items-center justify-center gap-2 text-xs text-warm-gray"><Wind size={14}/> Stop anytime and return when you feel ready.</div></div></> }
